import { inter } from '@/fonts'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable}`}
    >
      <body className='bg-neutral-200 dark:bg-dark-neutral-100'>
        {children}
      </body>
    </html>
  )
}
