import { PersonDetails } from '@/services/fetchPerson/fetchPerson';
import { ListsResponse, PopularPerson } from '@/services/types';

export const personDetailsData: PersonDetails = {
	adult: false,
	also_known_as: [
		'스칼릿 조핸슨',
		'سكارليت جوهانسون',
		'史嘉蕾·喬韓森',
		'สการ์เลตต์ โจแฮนส์สัน',
		'スカーレット・ヨハンソン',
		'斯嘉丽·约翰逊',
		'스칼렛 요한슨',
		'Σκάρλετ Τζοχάνσον',
		'Scarlett Ingrid Johansson',
		"סקרלט ג'והנסון",
		'اسکارلت جوهانسن',
		'สการ์เลตต์ อิงกริด โจแฮนส์สัน'
	],
	biography: 'Скарлетт Йоханссон — американская актриса и певица. Наибольшую известность ей принесло сотрудничество с Вуди Алленом («Матч-пойнт») и Софией Копполой («Трудности перевода»), а также роль Чёрной Вдовы в серии фильмов кинематографической вселенной Marvel.',
	birthday: '1984-11-22',
	deathday: null,
	gender: 1,
	homepage: null,
	id: 1245,
	imdb_id: 'nm0424060',
	known_for_department: 'Acting',
	name: 'Скарлетт Йоханссон',
	place_of_birth: 'New York City, New York, USA',
	popularity: 153.44,
	profile_path: '/3JTEc2tGUact9c0WktvpeJ9pajn.jpg',
	external_ids: {
		imdb_id: 'nm0424060',
		facebook_id: null,
		instagram_id: '',
		tiktok_id: null,
		twitter_id: null,
		youtube_id: null
	},
	combined_credits: {
		cast: [
			{
				adult: false,
				genre_ids: [28, 53, 878, 12],
				id: 1635,
				poster_path: '/lhULdzFbn2bD0FXdfyO1Y4yP4iF.jpg',
				release_date: '2005-07-21',
				title: 'Остров',
				vote_average: 6.7,
				vote_count: 5262,
				character: 'Jordan Two Delta / Sarah Jordan',
				media_type: 'movie',
				popularity: 103.11,
				original_title: 'The Island',
			},
			{
				adult: false,
				genre_ids: [18],
				id: 492188,
				poster_path: '/hGAgtvDF59ziLJviIfofAwofr5.jpg',
				release_date: '2019-09-28',
				title: 'Брачная история',
				vote_average: 7.742,
				vote_count: 6803,
				character: 'Nicole Barber',
				media_type: 'movie',
				popularity: 75.55,
				original_title: 'Marriage Story',
			},
		],
		crew: [
			{
				adult: false,
				genre_ids: [53],
				id: 1318454,
				poster_path: null,
				release_date: '',
				title: 'Sasha',
				vote_average: 0,
				vote_count: 0,
				department: 'Production',
				job: 'Producer',
				media_type: 'movie',
				popularity: 33.3,
				original_title: 'Sasha',
			},
			{
				adult: false,
				genre_ids: [99],
				id: 33833,
				poster_path: '/1R6pR4X5usNA7rPbt9q7a96S6HK.jpg',
				first_air_date: '1992-06-12',
				name: 'HBO: Первый взгляд ',
				vote_average: 4.9,
				vote_count: 10,
				department: 'Crew',
				job: 'Thanks',
				media_type: 'tv',
				popularity: 44.4,
				original_name: 'HBO First Look',
				episode_count: 5,
			},
		]
	}
};

export const personsData: ListsResponse<PopularPerson> =
{
	page: 1,
	results: [
		{
			adult: false,
			gender: 1,
			id: 1696016,
			known_for_department: 'Acting',
			name: 'Хлоя Коулмэн',
			popularity: 208.036,
			profile_path: '/rTbVFZMvUViFCIa5AXlBX3P6vfR.jpg',
			known_for: [{
				id: 700391,
				title: '65',
				poster_path: '/rzRb63TldOKdKydCvWJM8B6EkPM.jpg',
				media_type: 'movie',
				adult: false,
				genre_ids: [878, 28, 12, 53],
				release_date: '2023-03-02',
				vote_average: 6,
				vote_count: 2213,
				popularity: 103.015,
				original_title: '65',
			},
			{
				id: 592834,
				title: 'Мой шпион',
				poster_path: '/g6g0bbJKQj2wUM6bOFJVoHW7o1V.jpg',
				media_type: 'movie',
				adult: false,
				genre_ids: [10751, 28, 35],
				release_date: '2020-01-09',
				vote_average: 6.897,
				vote_count: 1149,
				popularity: 115.013,
				original_title: 'My Spy',
			}]
		},
		{
			adult: false,
			gender: 2,
			id: 64,
			known_for_department: 'Acting',
			name: 'Гэри Олдман',
			popularity: 185.241,
			profile_path: '/2v9FVVBUrrkW2m3QOcYkuhq9A6o.jpg',
			known_for: [{
				id: 155,
				title: 'Тёмный рыцарь',
				poster_path: '/dxWaYQtgpLbycqUpHzkqqYkT5I3.jpg',
				media_type: 'movie',
				adult: false,
				genre_ids: [18, 28, 80, 53],
				release_date: '2008-07-16',
				vote_average: 8.517,
				vote_count: 32255,
				popularity: 155.010,
				original_title: 'The Dark Knight',
			},
			{
				id: 49026,
				title: 'Тёмный рыцарь: Возрождение легенды',
				poster_path: '/9LfroB8zJD7HqP5hsxeDPHrzbw0.jpg',
				media_type: 'movie',
				adult: false,
				genre_ids: [28, 80, 18, 53],
				release_date: '2012-07-17',
				vote_average: 7.781,
				vote_count: 22313,
				popularity: 189.023,
				original_title: 'The Dark Knight Rises',
			}]
		}],
	total_pages: 176838,
	total_results: 3536758
};